<div style="text-align: justify; max-width: 90ch">

# Lecture 02d: Chroma, retrievers and the LangChain RAG chain

**Status: Mandatory reading.**

`lec_02b` searched a NumPy matrix of four lectures, rebuilt from a cache file. A real system keeps its vectors in a vector store,
which saves them with their text and metadata, and searches and filters them fast; [Chroma](https://docs.trychroma.com/) is one (section 1).

On top of it we build the LangChain RAG chain, then ask what every RAG system must answer: does retrieval find the right notes?

**What this notebook covers**

- A persistent Chroma index of all thirteen lectures.
- Ingesting once: why re-running a notebook must not double the index.
- Search with scores, a metadata filter and a content filter.
- The LangChain RAG chain.
- Measuring retrieval with **hit rate@k** and **MRR** on an evaluation set.
- **Query rewriting**, measured.

</div>

In [1]:
import json
import os
import time
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_ollama import ChatOllama, OllamaEmbeddings

from course_helpers.corpus import load_corpus
from course_helpers.rag import hit_rate_and_mrr, split_documents

In [2]:
# --- Course configuration: edit TIER only; settings in .env (Read: 01d_env_hugging_face) ---
TIER = "cpu"  # 8-16 GB RAM, no GPU (default)
# TIER = "gpu"  # >= 8 GB VRAM: bigger, better answers (pull qwen3:8b first)

REPO = Path.cwd().resolve().parents[1]  # runs from a lecture subfolder
load_dotenv(REPO / ".env")  # load your .env settings: OLLAMA_HOST, HF_TOKEN, ...
TIER = os.environ.get("COURSE_TIER", TIER)  # tools/run_all.py can override
from huggingface_hub.utils import disable_progress_bars

disable_progress_bars()  # no download bars in saved outputs (works after the imports)
CHAT_MODEL = {"cpu": "qwen3:1.7b", "gpu": "qwen3:8b"}[TIER]
EMBED_MODEL = "nomic-embed-text"
OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
MLFLOW_URI = os.environ.get("MLFLOW_TRACKING_URI", "http://127.0.0.1:5010")
# To override .env in this notebook only, uncomment and edit (never a token):
# OLLAMA_HOST = "http://192.168.1.20:11434"
# MLFLOW_URI = "http://127.0.0.1:5011"
EXPERIMENT = "llm-course-02-rag"
DATA_DIR = REPO / "data"  # gitignored runtime state (indexes, caches)

from course_helpers.checks import check_ollama

check_ollama(OLLAMA_HOST, [CHAT_MODEL])

Ollama OK at http://localhost:11434; models ready: qwen3:1.7b

<div style="text-align: justify; max-width: 90ch">

**Rebuild inputs.** All thirteen lectures, cut into chunks of 800 characters with an overlap of 100 (`lec_02c`), in two lines.

`split_documents` is not a new splitter: it wraps LangChain's `RecursiveCharacterTextSplitter`, the one `lec_02c` used, and adds three settings these notes need:

- **Headings-first separators:** `## ` and `### ` before paragraphs, lines and words, but not `# `, which starts a Python comment inside the notes' code blocks.
- **Short pieces dropped:** under 80 characters, such as a heading left alone, which would match every short question.
- **A `heading` in the metadata:** the nearest heading above each chunk, shown in the search results below.

**Why a wrapper:** lecture 3 and the exercises rebuild the same index, and the split must be identical every time, or the chunk ids and the evaluation results stop matching.
Real projects do the same: a library splitter inside one small project function.

</div>

In [3]:
documents = load_corpus(REPO / "corpus" / "uoa_py_course")

chunks = split_documents(documents, chunk_size=800, chunk_overlap=100)

print(f"{len(documents)} files -> {len(chunks)} chunks")

125 files -> 2452 chunks

<div style="text-align: justify; max-width: 90ch">

## 1. A vector store

A search starts from a query, and a vector store holds what it searches.

- A **query** is the text a search runs with, usually the user's question.
- A **database** is software that keeps data on disk for programs to search, add to and change.
- A **vector store** is a database for vectors: it stores each one with its text and metadata, and returns the nearest ones to a query.
- **Chroma** is an open-source vector store that runs inside Python and keeps its data in a folder ([docs](https://docs.trychroma.com/)).
- A **collection** is one named set of vectors inside a vector store, like a table in a database.
- An **id** is the unique name of one item, such as one stored chunk.
- An **index** is the searchable store of a set of documents' vectors, with a structure that finds near neighbours without comparing the query with every vector (not the index of a DataFrame).
  Chroma's structure is [HNSW](https://en.wikipedia.org/wiki/Hierarchical_navigable_small_world).

</div>

<div style="text-align: justify; max-width: 90ch">

Chroma keeps a collection between sessions in its persist directory, here `data/chroma/`. LangChain's retrievers (`lec_02b`) work on top of it:
any object that returns the documents for a question.

Chroma computes embeddings through an embedding function: `OllamaEmbeddings`, LangChain's wrapper around the same `nomic-embed-text`.
`"hnsw:space": "cosine"` makes the index compare vectors by cosine, as in `lec_02a`.

</div>

In [4]:
check_ollama(OLLAMA_HOST, [EMBED_MODEL])

embeddings = OllamaEmbeddings(model=EMBED_MODEL, base_url=OLLAMA_HOST)

store = Chroma(
    collection_name="course_notes",
    embedding_function=embeddings,
    persist_directory=str(DATA_DIR / "chroma"),
    collection_metadata={"hnsw:space": "cosine"},
)

print(f"{len(store.get(include=[])['ids'])} chunks stored so far")

Ollama OK at http://localhost:11434; models ready: nomic-embed-text

2452 chunks stored so far

<div style="text-align: justify; max-width: 90ch">

## 2. Ingest once

Adding documents embeds them and writes them to disk. But a notebook runs many times.

- **Ingestion** is loading documents into a vector store: cutting them into chunks, embedding the chunks and storing them.
- An **idempotent operation** is an operation whose result is the same after one run or after many.

Ingestion must be an idempotent operation. The mistake, on a throwaway collection kept in memory:

</div>

In [5]:
# WRONG: add the documents every time the cell runs
scratch = Chroma(
    collection_name="scratch", embedding_function=embeddings
)  # in memory only

for run in [1, 2]:
    scratch.add_documents(chunks[:5])
    print(f"after run {run}: {len(scratch.get(include=[])['ids'])} chunks")

scratch.delete_collection()  # clean up the demonstration

after run 1: 5 chunks
after run 2: 10 chunks

<div style="text-align: justify; max-width: 90ch">

Each run stores the five chunks again under new random ids. After ten runs of the notebook the index would hold every chunk ten times,
and a search would return four copies of the same text.

</div>

In [6]:
# RIGHT: embed only when the collection does not hold exactly these chunks, under stable ids
if len(store.get(include=[])["ids"]) != len(chunks):
    store.reset_collection()  # empty, half-built or out of date: start again
    started = time.time()

    for start in range(0, len(chunks), 256):
        batch = chunks[start : start + 256]
        ids = [f"{c.metadata['source']}#{c.metadata['start_index']}" for c in batch]
        store.add_documents(batch, ids=ids)
        print(f"{start + len(batch)} / {len(chunks)}")

    print(f"embedded in {time.time() - started:.0f} s")

print(f"{len(store.get(include=[])['ids'])} chunks in data/chroma")

2452 chunks in data/chroma

<div style="text-align: justify; max-width: 90ch">

The count check compares with the chunks we expect: an empty, half-built or out-of-date collection is rebuilt, a complete one is reused, so every later run is instant.

The ids (file and start position) stay the same while the file does, so adding a chunk again replaces it instead of duplicating it.
One change the count cannot see is a new embedding model: after changing `EMBED_MODEL`, delete `data/chroma/`. The same code is promoted as `course_helpers.rag.build_chroma_index`.

</div>

<div style="text-align: justify; max-width: 90ch">

## 3. Search with scores

`similarity_search_with_score` returns the nearest chunks with their cosine distance.

- **Cosine distance** is 1 minus the cosine similarity of two vectors (`lec_02a`): 0 for the same direction, so a lower distance means a closer chunk.

</div>

In [7]:
def build_results_table_from(results):
    """One row per (document, distance) pair returned by the store."""
    return pd.DataFrame(
        [
            {
                "distance": round(distance, 3),
                "source": doc.metadata["source"],
                "kind": doc.metadata["kind"],
                "heading": doc.metadata["heading"][:45],
            }
            for doc, distance in results
        ]
    )


build_results_table_from(
    store.similarity_search_with_score("Which lecture covers data leakage?", k=4)
)

,distance,source,kind,heading
0,0.340,lecture_01/instruct_01b_run_python.md,guide,instruct_01b_run_python.txt
1,0.357,lecture_10/lec_10_exercises.md,exercises,1. The basic KNN pipeline on a new dataset
2,0.363,lecture_07/practice_lec_07b_advanced_polars.md,lecture,practice_lec_07b_advanced_polars.txt
3,0.370,lecture_13/lec_13b_pipelines_preprocessing_mod...,lecture,2. The leakage problem

<div style="text-align: justify; max-width: 90ch">

Check each row: does the chunk explain leakage, or does it only share words such as "lecture" and "data" with the question?
Similarity measures closeness to the question's words and topic, not whether a chunk answers it. Now `lec_02b`'s two questions, on chunks.
First the one whose answer the 4,000-character cut lost:

</div>

In [8]:
HEART_QUESTION = "In the heart-disease screening example, what recall does the model reach at threshold 0.3?"

build_results_table_from(store.similarity_search_with_score(HEART_QUESTION, k=4))

,distance,source,kind,heading
0,0.244,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,Choosing the scoring metric
1,0.244,lecture_12/lec_12a_logistic_regression_intuiti...,lecture,Lower the decision threshold — different conf
2,0.247,lecture_12/lec_12a_logistic_regression_intuiti...,lecture,Lower the decision threshold — different conf
3,0.255,lecture_12/lec_12a_logistic_regression_intuiti...,lecture,Lower the decision threshold — different conf

<div style="text-align: justify; max-width: 90ch">

Look for `lec_12a` among the sources: its threshold table now sits in a chunk of its own, no longer cut off, so when retrieval finds it,
the answer can reach the prompt. Then the class name:

</div>

In [9]:
build_results_table_from(
    store.similarity_search_with_score("What does GridSearchCV do?", k=4)
)

,distance,source,kind,heading
0,0.368,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,`GridSearchCV`: search a grid automatically
1,0.372,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,`GridSearchCV`: search a grid automatically
2,0.381,lecture_13/goals_13.md,goals,Required
3,0.404,lecture_13/read_agents_automation_mlops.md,reading,"Task A1 — delegate the grid, verify by hand ("

<div style="text-align: justify; max-width: 90ch">

No empty headings any more: `lec_02c` dropped the pieces under 80 characters. Whether `lec_13a`, the notebook on `GridSearchCV`, ranks first depends on the embedding model and its version:
to the model the class name is still a few meaningless fragments (`lec_02c`). Section 4 makes that search reliable.

</div>

<div style="text-align: justify; max-width: 90ch">

## 4. Filters

Every chunk carries its file's `kind` (`lec_02c`):

- lecture notes
- setup guides
- exercises
- solutions
- goals
- "read_agents" readings

The last four restate the lectures in fewer words and may crowd the results; section 6 measures whether they do.

- A **metadata filter** is a search condition on a chunk's metadata, such as its `kind`, that keeps only the matching chunks.

The filter below keeps only the lecture notes and guides; `{"kind": {"$in": [...]}}` is Chroma's [filter language](https://docs.trychroma.com/docs/querying-collections/metadata-filtering) for "kind is one of these values":

</div>

In [10]:
LECTURE_NOTES = {"kind": {"$in": ["lecture", "guide"]}}

build_results_table_from(
    store.similarity_search_with_score(
        "What does GridSearchCV do?", k=4, filter=LECTURE_NOTES
    )
)

,distance,source,kind,heading
0,0.368,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,`GridSearchCV`: search a grid automatically
1,0.372,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,`GridSearchCV`: search a grid automatically
2,0.404,lecture_12/lec_12d_logistic_regression_hyperpa...,lecture,Lecture 12d — Logistic Regression: Hyperparam
3,0.419,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,Visualising the search

<div style="text-align: justify; max-width: 90ch">

The filter removes the readings and exercises, but it cannot make the embedding understand a class name: which chunks rank first still depends on the run.
When a question names an exact term, add a content filter.

- A **content filter** is a search condition on a chunk's text, such as containing an exact term, that keeps only the matching chunks.

`where_document={"$contains": ...}` keeps only chunks whose text contains the term, and the embedding ranks those.

</div>

In [11]:
build_results_table_from(
    store.similarity_search_with_score(
        "What does GridSearchCV do?",
        k=4,
        filter=LECTURE_NOTES,
        where_document={"$contains": "GridSearchCV"},
    )
)

,distance,source,kind,heading
0,0.368,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,`GridSearchCV`: search a grid automatically
1,0.372,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,`GridSearchCV`: search a grid automatically
2,0.404,lecture_12/lec_12d_logistic_regression_hyperpa...,lecture,Lecture 12d — Logistic Regression: Hyperparam
3,0.429,lecture_13/lec_13a_gridsearchcv_hyperparameter...,lecture,Choosing the scoring metric

<div style="text-align: justify; max-width: 90ch">

Every result now contains the exact word `GridSearchCV`, and the embedding ranks only those chunks. If the table matches the one above, the embedding had already ranked such chunks first on this run:
the filter guarantees the term, not a different ranking. Exact matching and meaning complement each other; production systems combine them automatically.

- **Hybrid search** is searching by exact words and by meaning at once, and combining the two rankings.

### ⏸ Pause point

When would a content filter hurt? Think of a misspelled class name, or a question that describes the idea without ever naming it (section 7).

</div>

<div style="text-align: justify; max-width: 90ch">

## 5. The LangChain RAG chain

`lec_01d` chained prompt, model and parser. A RAG chain adds a first step:

- The retriever (`lec_02b`) fetches four chunks.
- `format_context_from` turns them into text labelled with their sources.
- `RunnablePassthrough` forwards the question unchanged.

The dict at the start runs both branches on the same input. A plain function such as `format_context_from` becomes a chain step as soon as you pipe into it:
LangChain wraps it for you.

</div>

In [12]:
retriever = store.as_retriever(search_kwargs={"k": 4, "filter": LECTURE_NOTES})


def format_context_from(docs):
    """Turn retrieved Documents into the text block the prompt receives."""
    return "\n\n".join(
        f"[source: {d.metadata['source']}]\n{d.page_content}" for d in docs
    )

In [13]:
prompt = ChatPromptTemplate.from_template(
    "You answer questions about a Python course using only the notes below. "
    "If the notes do not contain the answer, say so. Mention the source file you used.\n\n"
    "Notes:\n{context}\n\nQuestion: {question}"
)

llm = ChatOllama(
    model=CHAT_MODEL,
    base_url=OLLAMA_HOST,
    reasoning=False,
    temperature=0,
    num_predict=200,
    num_ctx=8192,
)

rag_chain = (
    {"context": retriever | format_context_from, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

<div style="text-align: justify; max-width: 90ch">

One question through the whole chain: the retriever, the prompt and the model run in one call.

</div>

In [14]:
PANDAS_QUESTION = "Which lecture covers pandas?"

print(rag_chain.invoke(PANDAS_QUESTION))

The lecture that covers pandas is discussed in the **[User Guide](https://pandas.pydata.org/docs/user_guide/index.html)** section of the Pandas documentation. Specifically, the notes mention studying the **"10 minutes to pandas"** section from the User Guide.

Source file: `lecture_07/lec_07a_pandas_df_index_slice.md`

In [15]:
# The chunks the chain received: the same search returns the same chunks
pd.DataFrame(
    [
        {"source": d.metadata["source"], "heading": d.metadata["heading"]}
        for d in retriever.invoke(PANDAS_QUESTION)
    ]
)

,source,heading
0,lecture_07/lec_07a_pandas_df_index_slice.md,What is [pandas?](https://pandas.pydata.org/)
1,lecture_01/instruct_01b_run_python.md,instruct_01b_run_python.txt
2,lecture_12/lec_12f_SVM.md,§I — When SVM is the right tool
3,lecture_07/practice_lec_07b_advanced_polars.md,practice_lec_07b_advanced_polars.txt

<div style="text-align: justify; max-width: 90ch">

Read the answer critically: is the file it cites among the four chunks above, spelled as in their metadata, and does that chunk say what the answer claims?
A model can cite a file it never received, or a file named inside a chunk.

Calling the retriever again shows what it handed over, because a search is not a sampled answer: the same index and question return the same chunks.
That holds only while nothing changes; `lec_03a` shows what every step actually received, for every answer, with MLflow tracing.

### ⏸ Pause point

Compare the file the answer cites with the four sources: which step would you fix, the search or the answer?

</div>

<div style="text-align: justify; max-width: 90ch">

## 6. Measuring retrieval

One good answer proves nothing. We need many questions with known answers.

- An **evaluation set** is a set of questions with known good answers, used to measure a system on many questions instead of one.

`corpus/eval/qa_eval_set.jsonl` holds 19 questions about the notes, one JSON object per line, each with the file that answers it (`expected_source`) and the facts a good answer states (lecture 3 uses those).

</div>

In [16]:
eval_path = REPO / "corpus" / "eval" / "qa_eval_set.jsonl"

eval_set = [
    json.loads(line) for line in eval_path.read_text(encoding="utf-8").splitlines()
]

pd.DataFrame(eval_set)[["id", "question", "expected_source"]].head()

,id,question,expected_source
0,q01,Which lecture explains data leakage in preproc...,lecture_13/lec_13b_pipelines_preprocessing_mod...
1,q02,What does GridSearchCV do?,lecture_13/lec_13a_gridsearchcv_hyperparameter...
2,q03,When should I use RandomizedSearchCV instead o...,lecture_13/lec_13a_gridsearchcv_hyperparameter...
3,q04,How do I log a metric in an MLflow run?,lecture_13/lec_13c_mlflow_tracking_basics.md
4,q05,How can MLflow record a whole hyperparameter s...,lecture_13/lec_13e_mlflow_logging_sweeps.md

<div style="text-align: justify; max-width: 90ch">

Two numbers summarise retrieval:

- **Hit rate@k** is the share of the questions for which a chunk of the file that answers the question is among the top `k` results.
- **Mean reciprocal rank (MRR)** is the average of 1 divided by the rank of the first chunk from the file that answers the question:
  1 if it is always first, 0.5 if always second, 0 if it is not in the top 8.

</div>

In [17]:
def find_source_rank_in(docs, expected_source):
    """Position (1 = first) of the first chunk from the expected file, or None."""
    for position, doc in enumerate(docs, start=1):
        if doc.metadata["source"] == expected_source:
            return position
    return None


rows, ranks_by_search = [], {}

for label, search_filter in [
    ("all chunks", None),
    ("lecture notes only", LECTURE_NOTES),
]:
    ranks = [
        find_source_rank_in(
            store.similarity_search(q["question"], k=8, filter=search_filter),
            q["expected_source"],
        )
        for q in eval_set
    ]
    row = {"search": label}
    for k in [1, 2, 4, 8]:
        row[f"hit@{k}"] = sum(r is not None and r <= k for r in ranks) / len(ranks)
    row["MRR"] = sum(1 / r for r in ranks if r) / len(ranks)
    rows.append(row)
    ranks_by_search[label] = ranks

pd.DataFrame(rows).round(2)

               search  hit@1  hit@2  hit@4  hit@8   MRR
0          all chunks   0.68   0.89    1.0    1.0  0.82
1  lecture notes only   0.84   0.89    1.0    1.0  0.90

<div style="text-align: justify; max-width: 90ch">

Compare the two rows: does the filter lift the top ranks (hit@1, MRR)? Does a larger `k` beyond 4 still add much? Every question whose file is not in the top four is listed below;
the list changes with the model version, and may be empty:

</div>

In [18]:
for q, rank in zip(eval_set, ranks_by_search["lecture notes only"]):
    if rank is None or rank > 4:
        print(f"{q['id']} {rank} {q['question']}")

<div style="text-align: justify; max-width: 90ch">

In example runs the misses, when there were any, were the questions that name a class: `GridSearchCV` (q02) and `RandomizedSearchCV` (q03).
With the content filter of section 4, each on its own class name:

</div>

In [19]:
EXACT_TERMS = {"q02": "GridSearchCV", "q03": "RandomizedSearchCV"}

for q in eval_set:
    if q["id"] in EXACT_TERMS:
        docs = store.similarity_search(
            q["question"],
            k=8,
            filter=LECTURE_NOTES,
            where_document={"$contains": EXACT_TERMS[q["id"]]},
        )
        filtered_rank = find_source_rank_in(docs, q["expected_source"])
        print(f"{q['id']} rank with the content filter: {filtered_rank}")

q02 rank with the content filter: 1
q03 rank with the content filter: 1

<div style="text-align: justify; max-width: 90ch">

In example runs both ranked in the top four with the content filter. The course uses `k=4` with the lecture filter: in example runs, the right file for 17 to 19 of the 19 questions, at under 1,000 tokens of notes per prompt.
Three limits of these numbers:

- **Few questions**: one question moves the hit rate by 5 points.
- **One expected file per question**: a search that finds a goals or exercise file that also answers is scored as a miss,
  part of why "all chunks" can score lower.
- **Choices tuned on the test**: the same 19 questions chose `k` and the filter, and will grade the system in lecture 3.
  That is the leakage of `lec_13b` (question q01!) in a new form: a larger project keeps separate questions for choosing and for grading.

They also measure retrieval only; whether the *answer* is right is lecture 3.

</div>

<div style="text-align: justify; max-width: 90ch">

`find_source_rank_in`, `format_context_from` and the ingestion guard are promoted to `course_helpers.rag` (with `hit_rate_and_mrr` and `make_rag_chain`),
ready for lecture 3.

</div>

<div style="text-align: justify; max-width: 90ch">

## 7. A question in the student's words

The content filter of section 4 needs the exact term. A student who has forgotten the term asks in their own words, and the search compares those words with the notes'.

- **Query rewriting** is a model call before the search that turns the question into a query in the documents' terms.

The price is that call, on every question. Six questions of the evaluation set, as a student might ask them without the term;
each `id` points to the original question and its expected file:

</div>

In [20]:
STUDENT_WORDING = {
    "q19": "Why can't I change an item of something written in round brackets?",
    "q15": "I built a little web demo of my model, how can my classmates open it from their own laptops?",
    "q09": "How do I stop a regression from giving huge weights to some of my columns?",
    "q10": "Why do my nearest-neighbour predictions change when I measure height in centimetres instead of metres?",
    "q02": "How can scikit-learn try every combination of my model's settings for me?",
    "q16": "How do I pick rows of a table by their position number instead of by their name?",
}
expected_source_of = {q["id"]: q["expected_source"] for q in eval_set}


def rank_of_expected_file_for(query, question_id):
    """Rank (1 = first, of 8) of the expected file's first chunk for this query, or None."""
    docs = store.similarity_search(query, k=8, filter=LECTURE_NOTES)
    return find_source_rank_in(docs, expected_source_of[question_id])


pd.DataFrame(
    [
        {
            "id": qid,
            "question": text,
            "rank as asked": rank_of_expected_file_for(text, qid),
        }
        for qid, text in STUDENT_WORDING.items()
    ]
).convert_dtypes()  # whole-number ranks, <NA> when not found

    id                                           question  rank as asked
0  q19  Why can't I change an item of something writte...              2
1  q15  I built a little web demo of my model, how can...              4
2  q09  How do I stop a regression from giving huge we...              2
3  q10  Why do my nearest-neighbour predictions change...              8
4  q02  How can scikit-learn try every combination of ...           <NA>
5  q16  How do I pick rows of a table by their positio...              1

<div style="text-align: justify; max-width: 90ch">

A rank above 4, or `<NA>` (not among the first eight), means the chain of section 5, which reads four chunks, never sees the expected file.
Compare with section 6, where the same questions in the notes' words ranked near the top.

The rewrite is a small chain (`lec_01d`). The prompt asks for the notes' terms and for the query only, so the answer can go straight into the search:

</div>

In [21]:
REWRITE_PROMPT = (
    "Rewrite the question below as a short search query for the notes of a Python course, "
    "with the technical terms the notes would use. Reply with the query only."
    "\n\nQuestion: {question}"
)
rewrite_query = (
    ChatPromptTemplate.from_template(REWRITE_PROMPT) | llm | StrOutputParser()
)

rows = []

for qid, text in STUDENT_WORDING.items():
    query = rewrite_query.invoke(text).strip()
    rows.append(
        {
            "id": qid,
            "query": query,
            "rank as asked": rank_of_expected_file_for(text, qid),
            "rank rewritten": rank_of_expected_file_for(query, qid),
        }
    )

pd.DataFrame(rows).convert_dtypes()

,id,query,rank as asked,rank rewritten
0,q19,why can't i change an item of something writte...,2,1
1,q15,How can I share a local web demo of my model w...,4,3
2,q09,How do I prevent regression from assigning lar...,2,1
3,q10,Why do nearest-neighbour predictions change wh...,8,6
4,q02,How can scikit-learn try every combination of ...,<NA>,<NA>
5,q16,how to select rows from a table by their posit...,1,1

<div style="text-align: justify; max-width: 90ch">

Read each query: did the model supply the term the student lacked, such as *tuple*, *Gradio*, *Ridge*, *scaling*, `GridSearchCV` or `iloc`?
Then compare the two rank columns.

In example runs on the `cpu` tier, rewriting moved some questions up and left others where they were; with `qwen3:8b` it found more of them, and moved one down.
Read your own rows.

A fix must also not break what already works. The same rewrite on the 19 questions of section 6, which already use the notes' words:

</div>

In [22]:
rewritten_ranks = [
    rank_of_expected_file_for(rewrite_query.invoke(q["question"]).strip(), q["id"])
    for q in eval_set
]

pd.DataFrame(
    {
        "as asked": hit_rate_and_mrr(ranks_by_search["lecture notes only"]),
        "rewritten": hit_rate_and_mrr(rewritten_ranks),
    }
).T.round(2)

           hit@1  hit@2  hit@4  hit@8   MRR
as asked    0.84   0.89    1.0    1.0  0.90
rewritten   0.74   0.89    1.0    1.0  0.85

<div style="text-align: justify; max-width: 90ch">

In example runs on both tiers, the rewritten queries put the right file first less often (a lower `hit@1`): a rewrite can drop a word the notes do use.
Rewriting is a trade-off, and only a measurement on your users' questions settles it.

### ⏸ Pause point

Would you add the rewrite step to the course's chain? Decide from the two tables before reading the decision record below.

</div>

<div style="text-align: justify; max-width: 90ch">

The decision, recorded like those of `lec_01b` and `lec_01d`:

- **Decision:** no rewrite step in the course's chain; it searches with the student's words.
- **Requirements:** the right notes for questions in the students' own words, without losing the questions that already work;
  one more model call per question.
- **Evidence:** the two tables of this section, in example runs on both tiers.
- **Worth it when:** users' words differ from the documents', and the model reliably supplies the terms, measured on questions in your users' words.
- **Not worth it when:** the questions already match the documents, or one more call per question costs too much time.
- **Revisit when:** the model, the questions or the documents change. The optional `lec_03e` adds a check: a model grades the search and tries another query when it missed.

`make_rag_chain(retriever, llm, rewriter=make_query_rewriter(llm))` from `course_helpers.rag` builds the chain with the rewrite,
for your own measurements.

</div>

<div style="text-align: justify; max-width: 90ch">

## Recap

- A **vector store** keeps vectors with their text and metadata in a named **collection**, and returns the nearest ones to a query.
- **Ingestion** must be an **idempotent operation**: check the count before embedding, and give chunks stable ids.
- A **metadata filter** removes whole kinds of documents; a **content filter** adds an exact-word condition the embedding cannot provide.
- The RAG chain is `{"context": retriever | format_context_from, "question": RunnablePassthrough()} | prompt | llm | parser`;
  `retriever.invoke` shows the chunks it received.
- **Hit rate@k** and **MRR** on an evaluation set with expected sources turn "it seems to work" into numbers you can compare.
- **Query rewriting** helps some questions in users' own words and can hurt questions that already match the notes: measure before you adopt it.

**Next: lecture 3**, which keeps every step with MLflow tracing and judges the answers themselves, not only the retrieval behind them.

</div>